### ISSUE TITLE
Unable to install PageBot with Terminal

### ISSUE THREAD

**Issue by eightmoe** [PageBot/PageBot#163]
Trying to install PageBot via _sudo python3 setup.py install_ prints a **SyntaxError for line 30 of elements/views/pagemapview.py** (missing underscore in "RIGHT ECI_GrayConL"?) and then ends after multiple errors similiar to:

sass.cpp:2224:24: error: no member named 'exc_type' in '_ts'
    tmp_type = tstate->exc_type;

Is there something I am doing wrong or missing?

**Comment by michielkauwatjoe** [comment]
@eightmoe Hi, thanks for reporting, should be fixed now. Could you try again?

**Comment by michielkauwatjoe** [comment]
@eightmoe On second thought, apparently the setup script still referenced another implementation of `sass`, not `libsass`.  Running `setup.py` again should not invoke Cython anymore; could you give it another run?

**Comment by eightmoe** [comment]
@michielkauwatjoe The last update made it: successfully installed with Python 3.7.
Thanks a lot!

**Comment by michielkauwatjoe** [comment]
@eightmoe Great, thank you for testing!
