### ISSUE TITLE
Install script not working, import error

### ISSUE THREAD

**Issue by sannorozco** [PageBot/PageBot#167]
Hi @michielkauwatjoe, while running install script, get this traceback:

Computer1:PageBot SO$ sudo python3 setup.py install
Traceback (most recent call last):
 File “setup.py”, line 15, in <module>
   from setuptools import setup, find_packages
ModuleNotFoundError: No module named ‘setuptools’
Computer1:PageBot SO$

**Comment by michielkauwatjoe** [comment]
@sannorozco @petrvanblokland The setuptools package is missing, you should be able to install it with pip:

    pip3 install setuptools

However we usually link to the source folder in a pth file so we don't need to reinstall it for every change. My `/Library/Python/3.6/site-packages/sources.pth` file for example has this line:

    /Users/michiel/Code/PageBot/Lib/

**Comment by justvanrossum** [comment]
`pip install -e .` is way more convenient that a pth file. Do this in the folder containing the setup.py of the project you want to install. Still will need setuptools, though.

**Comment by sannorozco** [comment]
Alright, with pip3, PageBot installed without errors, 

thanks!
